# Generated by Django 4.2.1 on 2023-05-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Caior'),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='Egyptian', max_length=50, null=True),
        ),
    ]
